name: Update Fronts (SimplyPlural → fronts.json)

on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 min
  workflow_dispatch: {}

permissions:
  contents: write

env:
  PAGES_BRANCH: main
  PAGES_DIR: .

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pages branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PAGES_BRANCH }}
          fetch-depth: 0

      - name: "Debug: show branch & tree"
        shell: bash
        run: |
          echo "On branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "Repo root contents:"; ls -la
          echo "PAGES_DIR contents:"; ls -la "${{ env.PAGES_DIR }}" || true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch fronters (self) → fronts.json
        shell: bash
        env:
          SP_TOKEN: ${{ secrets.SP_TOKEN }}
          PAGES_DIR: ${{ env.PAGES_DIR }}
        run: |
          set -euo pipefail
          test -n "${SP_TOKEN}" || { echo "ERROR: SP_TOKEN secret is not set"; exit 1; }
          mkdir -p "${PAGES_DIR}"

          URL="https://api.apparyllis.com/v1/fronters/self"
          echo "Fetching: $URL"

          CODE=$(curl -sS -D "${PAGES_DIR}/resp.hdr" -o "${PAGES_DIR}/resp.json" -w "%{http_code}" \
            -H "Authorization: ${SP_TOKEN}" \
            -H "Accept: application/json" \
            -H "Cache-Control: no-cache" \
            "${URL}" || true)

          echo "HTTP ${CODE}"
          if [ "${CODE}" != "200" ]; then
            echo "Headers:"; sed -n '1,40p' "${PAGES_DIR}/resp.hdr" || true
            echo "Body:"; head -c 400 "${PAGES_DIR}/resp.json" || true; echo
            exit 1
          fi

          jq -S . "${PAGES_DIR}/resp.json" > "${PAGES_DIR}/fronts.json"
          echo "Wrote $(wc -c < "${PAGES_DIR}/fronts.json") bytes to fronts.json"

      - name: Show first 400 chars of fronts.json (debug)
        shell: bash
        env:
          PAGES_DIR: ${{ env.PAGES_DIR }}
        run: |
          head -c 400 "${PAGES_DIR}/fronts.json" || true
          echo

      - name: Validate JSON
        shell: bash
        env:
          PAGES_DIR: ${{ env.PAGES_DIR }}
        run: |
          python -c "import json; json.load(open('${{ env.PAGES_DIR }}/fronts.json')); print('fronts.json is valid JSON')"

      - name: Commit and push if changed
        shell: bash
        env:
          PAGES_BRANCH: ${{ env.PAGES_BRANCH }}
          PAGES_DIR: ${{ env.PAGES_DIR }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${PAGES_DIR}/fronts.json"
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update fronts.json [skip ci]"
          git push origin "${PAGES_BRANCH}"
